name: Tic-Tac-Toe CI

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  build-linux:
    name: Build and Test (Linux)
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Install Qt and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake qtbase5-dev qt5-qmake qtbase5-dev-tools libqt5test5

    - name: Create Build Directory
      run: mkdir build
      
    - name: Configure CMake
      working-directory: build
      run: cmake ..

    - name: Build
      working-directory: build
      run: cmake --build .

    - name: Run Tests
      working-directory: build
      run: ctest --output-on-failure
      
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      with:
        name: test-results-linux
        path: build/Testing/Temporary/LastTest.log
        if-no-files-found: ignore

  build-windows:
    name: Build and Test (Windows)
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Setup MSVC environment
    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
      
    # Install Qt using the official installer
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.15.2'
        
    # Debug info
    - name: Debug Qt installation
      run: |
        echo "Qt installation directory: $env:Qt5_DIR"
        dir $env:Qt5_DIR -ErrorAction SilentlyContinue
        echo "QTDIR: $env:QTDIR"
        dir $env:QTDIR -ErrorAction SilentlyContinue
        
    - name: Create Build Directory
      run: mkdir build
      
    - name: Configure CMake
      working-directory: build
      run: |
        echo "Using Qt from: $env:Qt5_DIR"
        cmake .. -G "Visual Studio 17 2022" -A x64

    - name: Build
      working-directory: build
      run: cmake --build . --config Release

    - name: Run Tests
      working-directory: build
      run: ctest -C Release --output-on-failure
      
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      with:
        name: test-results-windows
        path: build/Testing/Temporary/LastTest.log
        if-no-files-found: ignore 